esphome:
  name: "level1"
  friendly_name: "level1"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Ln5+pbq5OQ5a1+7Kcq5jD237VpLyCv3uxSukxfv47pM="

ota:
  password: "27d2adda1d52b6a0363d02f65eb14108"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dht22 Fallback Hotspot"
    password: "82ObWqLjfsDk"


uart:
  rx_pin: GPIO22
  tx_pin: GPIO21
  baud_rate: 9600
 

captive_portal:


sensor:
  - platform: dht
    pin: GPIO4
    temperature:
      name: "Level 1 Temperature"
    humidity:
      name: "Level 1 Humidity"
    update_interval: 10s
  - platform: mhz19
    co2:
      name: "co2 level 1 "
    temperature:
      name: "MHZ19 Temperature"
    update_interval: 10s
    